name: CI - MLflow Training Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  training:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install Dependencies
        run: |
          pip install mlflow==2.19.0 scikit-learn pandas numpy dagshub matplotlib

      - name: Setup DagsHub Credentials
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/shandylatoz851/Obesity-MLflow.mlflow" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=shandylatoz851" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Run MLflow Project
        env:
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ env.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ env.MLFLOW_TRACKING_PASSWORD }}
        run: |
          cd MLProject
          mlflow run . --env-manager=local \
            -P n_estimators=200 \
            -P max_depth=10 \
            -P min_samples_split=5

      - name: Upload Artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            MLProject/confusion_matrix.png
            MLProject/classification_report.json

      - name: Commit Artifact to Repository
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add MLProject/confusion_matrix.png MLProject/classification_report.json
          git diff --staged --quiet || git commit -m "Auto: update model artifacts"
          git push